//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LukeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note_Type
    {
        public Note_Type()
        {
            this.Notes = new HashSet<Note>();
        }
    
        public int note_type_id { get; set; }
        public string note_type_description { get; set; }
    
        public virtual ICollection<Note> Notes { get; set; }
    }
}
