//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LukeMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Luke2432Entities : DbContext
    {
        public Luke2432Entities()
            : base("name=Luke2432Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Note_Type> Note_Type { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<verse_category> verse_category { get; set; }
        public virtual DbSet<verse_category_log> verse_category_log { get; set; }
    }
}
