//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LukeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int note_id { get; set; }
        public int note_type_id { get; set; }
        public string note_title { get; set; }
        public string passage { get; set; }
        public string note_body { get; set; }
        public string user { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
    
        public virtual Note_Type Note_Type { get; set; }
    }
}
