//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LukeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class verse_category
    {
        public verse_category()
        {
            this.verse_category_log = new HashSet<verse_category_log>();
        }
    
        public int verse_category_id { get; set; }
        public string verse_category_name { get; set; }
        public string active { get; set; }
        public string text_color_name { get; set; }
        public string text_color_code { get; set; }
        public string text_size { get; set; }
        public string text_bold { get; set; }
        public string background_color_name { get; set; }
        public string background_color_code { get; set; }
        public string css_class_name { get; set; }
        public string user_id { get; set; }
        public string verse_category_description { get; set; }
    
        public virtual ICollection<verse_category_log> verse_category_log { get; set; }
    }
}
